### ISSUE TITLE
Contract selection - voting here

### ISSUE THREAD

**Issue by servo270** [Halibut-Aircraft-Design/project-alpha#4]
Which contract interests you the most?

- 1944 stopgap interceptor

- early 1950's seaplane supersonic fighter

- 1960s next-generation penetration bomber

Place your votes and reasoning in the comments. Leave a first and second choice, votes will be counted as 2pts per #1 vote and 1pt per #2 vote

**Comment by servo270** [comment]
#1 - 1944 interceptor. Still biased because there's a lot of cool engine work we can do here
#2 - seaplane fighter. Hard challenges are fun challenges

**Comment by Jean-Alexander** [comment]
#1 - seaplane fighter: Seems rather difficult to make at all practical
#2 - 1944 Interceptor: Interesting options for propulsion

**Comment by Pieliker96** [comment]
#1: seaplane supersonic fighter, because it's hard.
#2: bomber, because a bigboi plane sounds fun.

**Comment by ConnieTheTomcat** [comment]
#1: seaplane fighter because it's cool
#2: bomber, because blowing things up is fun

**Comment by Mendrin-Ceibaleaf** [comment]
N°1 - Seaplane fighter, because seaplanes are cool
N°2 - Interceptor, as it sounds more original than a bomber

**Comment by OceanTerry** [comment]
#1: 1950s seaplane supersonic fighter
#2: 1960s bomber
